state_abr = function(x){
  x = case_when(
  x ==   1 ~	"AL",
  x ==   2 ~	"AK",
  x ==   3 ~	"AZ",
  x ==   4 ~	"AR",
  x ==   5 ~	"CA",
  x ==   6 ~	"CO",
  x ==   7 ~	"CT",
  x ==   8 ~	"DE",
  x ==   9 ~	"FL",
    x == 10 ~	"GA",
    x == 11 ~	"HI",
    x == 12 ~	"ID",
    x == 13 ~	"IL",
    x == 14 ~	"IN",
    x == 15 ~	"IA",
    x == 16 ~	"KS",
    x == 17 ~	"KY",
    x == 18 ~	"LA",
    x == 19 ~	"ME",
    x == 20 ~	"MD",
    x == 21 ~	"MA",
    x == 22 ~	"MI",
    x == 23 ~	"MN",
    x == 24 ~	"MS",
    x == 25 ~	"MO",
    x == 26 ~	"MT",
    x == 27 ~	"NE",
    x == 28 ~	"NV",
    x == 29 ~	"NH",
    x == 30 ~	"NJ",
    x == 31 ~	"NM",
    x == 32 ~	"NY",
    x == 33 ~	"NC",
    x == 34 ~	"ND",
    x == 35 ~	"OH",
    x == 36 ~	"OK",
    x == 37 ~	"OR",
    x == 38 ~	"PA",
    x == 39 ~	"RI",
    x == 40 ~	"SC",
    x == 41 ~	"SD",
    x == 42 ~	"TN",
    x == 43 ~	"TX",
    x == 44 ~	"UT",
    x == 45 ~	"VT",
    x == 46 ~	"VA",
    x == 47 ~	"WA",
    x == 48 ~	"WV",
    x == 49 ~	"WI",
    x == 50 ~	"WY",
  TRUE ~ NA_character_
  )
}
