---
title: "Create weekly scripts"
output: html_document
---

```{r 00-weekly-reports-1}
library(here)
library(openintro)
source(here("Scripts/score data.R"))
```

```{r 00-weekly-reports-2}
states = scored %>% 
  group_by(CaregiverID) %>% 
  filter(Week == max(Week)) %>%
  ungroup() %>%
  group_by(state) %>%
  summarize(n = n()) %>%
  filter(n > 200) %>%
  mutate(name = map_chr(state, abbr2state),
         title = paste("RAPID analysis of", name))

```


```{r 00-weekly-reports-4}
for (state_sub in 1:nrow(states)) {
  rmarkdown::render("state_specific.Rmd", 
                    params = list(mainstate = states$state[state_sub],
                                  title = states$title[state_sub]),
                    output_file=paste0("state_",states$state[state_sub], "_report.html"))
}
```



```{r 00-weekly-reports-3, eval = F}
source(here("Scripts/score data.R"))

all_weeks = scored %>%
  filter(Week > 0) %>%
  group_by(Week) %>%
  summarize(start = min(Date),
            stop = max(Date),
            start = format(start, "%B %d"),
            stop = format(stop, "%B %d")) %>%
  rowwise() %>%
  mutate(title  = paste0("Week ", Week, " (", start, " - ", stop, ") Summary"))

for (week_sub in 1:nrow(all_weeks)) {
  rmarkdown::render("_weekly_report.Rmd", 
                    params = list(subset = all_weeks$Week[week_sub],
                                  title = all_weeks$title[week_sub]),
                    output_file=paste0("week",week_sub, "_report.html"))
}
```