---
title: "Who is participating?"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: paper
---

```{r, echo = F}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '')
```

```{r packages}
library(here)
library(tsibble)
library(brolgar)
```

```{r score datafile, echo = F, warning = F, message = F}
source(here("Scripts/score data.R"))
```


```{r, key demographics}
source(here("Scripts/demo groups.R"))
```

```{r}
max_weeks = max(scored$Week, na.rm=T)
start_dates = seq(as.Date("2020-04-07"), by = 7, length.out = max_weeks)
end_dates = seq(as.Date("2020-04-13"), by = 7, length.out = max_weeks)
start_dates[1] = as.Date("2020-04-06")

start_dates = format(start_dates, format = "%B %d")
end_dates = format(end_dates, format = "%B %d")

all_dates = paste(start_dates, "-", end_dates)
```

# Across all parents sampled

```{r, results = 'asis'}
scored %>%
  filter(Week > 0) %>%
  group_by(CaregiverID) %>%
  filter(Week == min(Week)) %>%
  ungroup() %>%
  select(all_of(binary_demos)) %>%
  gather("Demographic", "value") %>%
  group_by(Demographic) %>%
  summarize(Count = sum(value,na.rm=T),
            total = n()) %>%
  mutate(Demographic = factor(Demographic, 
                              levels = binary_demos, 
                              labels = binary_labels),
         Percent = 100*Count/total) %>%
  select(Demographic, Count, Percent) %>%
  kable(., col.names = c("Demographic", "Count", "Percent of sample"),
        digits = c(0,0,1)) %>%
  kable_styling() %>%
  scroll_box(width = "650px")
```

## Income

```{r}
source(here("Functions/income_levels.R"))
```

```{r, results = 'asis'}
scored %>%
  filter(Week > 0) %>%
  group_by(CaregiverID) %>%
  filter(Week == min(Week)) %>%
  ungroup() %>%
  filter(!is.na(income)) %>%
  summarize(Mean = mean(income),
            Median = median(income),
            Bottom10 = quantile(income, probs = c(.10)),
            Top10 = quantile(income, probs = c(.90))) %>%
  kable(., col.names = c("Average", "Median", "Lowest 10%", "Top 10%")) %>%
  kable_styling()
```


```{r, results = 'asis'}
scored %>%
  filter(Week > 0) %>%
  group_by(CaregiverID) %>%
  filter(Week == min(Week)) %>%
  ungroup() %>%
  filter(!is.na(income)) %>%
  mutate(income_cat = income_levels(income, num_levels = 25)) %>%
  group_by(income_cat) %>%
  summarize(Count = n()) %>%
  ungroup() %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  kable(., 
        col.names = c("Income (in thounsands per year)", "Count", "Percent"), 
        digits = c(0,0,1)) %>%
  kable_styling()
```

## Healthcare

```{r, results = 'asis'}
source(here("Scripts/health variables.R"))
scored %>%
  filter(Week > 0) %>%
  group_by(CaregiverID) %>%
  filter(Week == min(Week)) %>%
  ungroup() %>%
  select(healthcare_vars) %>%
  gather("variable", "value") %>%
  group_by(variable) %>%
  summarize(Count = sum(value,na.rm=T),
            total = n()) %>%
  mutate(variable = factor(variable, 
                              levels = healthcare_vars, 
                              labels = healthcare_labels),
         Percent = 100*Count/total) %>%
  select(variable, Count, Percent) %>%
  kable(., col.names = c("Variable", "Count", "Percent of sample"),
        digits = c(0,0,1)) %>%
  kable_styling() %>%
  scroll_box(width = "650px")
```


## Comparisons with national demographics {.tabset}

```{r}
pop = read_sav(here("../../Data Management R3/CC_Clean Survey Data/00_R3 MasterFile/Population_Estimates.sav"))
pop = pop %>%
  mutate(region = case_when(
    Region == 1 ~ "Northeast",
    Region == 2 ~ "Midwest",
    Region == 3 ~ "South",
    Region == 4 ~ "West"
  ))

scored_first = scored %>%
  filter(Week > 0) %>%
  group_by(CaregiverID) %>%
  filter(Week == min(Week)) %>%
  ungroup() 
```

### Gender

```{r, out.width='100%'}
sample_gender = scored_first %>%
  filter(!is.na(gender) & !is.na(region)) %>%
  group_by(gender, region) %>%
  summarize(Count = n()) %>%
  group_by(region) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID")

#pop_gender = 
  
pop %>%
    filter(!is.na(region)) %>%
  select(region, TotalPop.Count, Male.Count, Female.Count) %>%
  gather(gender, count, -region) %>%
    group_by(region, gender) %>%
    summarize(count = sum(count)) %>%
    spread(gender, count) %>%
    mutate(Female.Percent = 100*Female.Count/TotalPop.Count,
           Male.Percent = 100*Male.Count/TotalPop.Count,
           Other.Percent = 100*(TotalPop.Count - Female.Count - Male.Count)/TotalPop.Count) %>%
    select(region, contains("Percent")) %>%
    gather("gender", "Percent", contains("Percent")) %>%
    mutate(gender = gsub("\\.Percent", "", gender)) %>%
    mutate(group = "US Population") %>%
    full_join(sample_gender) %>%
  ggplot(aes(x = region, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 5), position = position_dodge(1)) +
  facet_grid(.~gender) +
  labs(x = "", fill = "")+
  theme_minimal(base_size = 10)+
  theme(legend.position = "top")
```

### Nationality

```{r, out.width='100%'}
nation = c(
"native",
"asian",
"black",
"hawaii",
"white",
"other",
"multiple")

nation_labels = c(
"American Indian/Alaska Native",
"Asian",
"Black/African American",
"Native Hawaiian/Pacific Islander",
"White/Caucasian",
"Other race",
"Multiple races")

nation_labels_breaks = c(
"American Indian/\nAlaska Native",
"Asian",
"Black/\nAfrican American",
"Native Hawaiian/\nPacific Islander",
"White\nCaucasian",
"Other\nrace",
"Multiple\nraces")


sample_nation = scored_first %>%
  filter(!is.na(race_cat))%>%
  group_by(race_cat) %>%
  summarize(Count = n()) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID")

pop %>%
  select(TotalPop.Count, 
         (contains("Race") & contains("Count"))) %>%
  gather(demo, count) %>%
    group_by(demo) %>%
    summarize(count = sum(count)) %>%
    spread(demo, count) %>%
    mutate(native.Percent = 100*Race.Amer.Ind.Count/TotalPop.Count,
           asian.Percent = 100*Race.Asian.Count/TotalPop.Count,
           black.Percent = 100*Race.Black.Count/TotalPop.Count,
           hawaii.Percent = 100*Race.Nat.HI.Count/TotalPop.Count,
           white.Percent = 100*Race.White.Count/TotalPop.Count,
           other.Percent = 100*Race.Other.Count/TotalPop.Count,
           ) %>%
    gather("demo", "Percent", contains("Percent")) %>%
    mutate(demo = gsub("\\.Percent", "", demo),
           race_cat = factor(demo, levels = nation, labels = nation_labels)) %>%
  select(race_cat, Percent) %>%
    mutate(group = "US Population") %>%
    full_join(sample_nation) %>%
  mutate(race_cat = factor(race_cat, 
                           levels = nation_labels, 
                           labels = nation_labels_breaks)) %>%
  ggplot(aes(x = race_cat, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 5), position = position_dodge(1)) +
  labs(x = "", fill = "")+
  theme_minimal(base_size = 10)+
  theme(legend.position = "top") 
```

### Nationality by region

```{r, out.width='100%'}

sample_nation = scored_first %>%
  filter(!is.na(race_cat) & !is.na(region)) %>%
  group_by(race_cat, region) %>%
  summarize(Count = n()) %>%
  group_by(region) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID")

pop %>%
  filter(!is.na(region)) %>%
  select(region, TotalPop.Count, 
         (contains("Race") & contains("Count"))) %>%
  gather(demo, count, -region) %>%
    group_by(region, demo) %>%
    summarize(count = sum(count)) %>%
    spread(demo, count) %>%
    mutate(native.Percent = 100*Race.Amer.Ind.Count/TotalPop.Count,
           asian.Percent = 100*Race.Asian.Count/TotalPop.Count,
           black.Percent = 100*Race.Black.Count/TotalPop.Count,
           hawaii.Percent = 100*Race.Nat.HI.Count/TotalPop.Count,
           white.Percent = 100*Race.White.Count/TotalPop.Count,
           other.Percent =100*Race.Other.Count/TotalPop.Count
           ) %>%
    select(region, contains("Percent")) %>%
    gather("demo", "Percent", contains("Percent")) %>%
    mutate(demo = gsub("\\.Percent", "", demo),
           race_cat = factor(demo, 
                             levels = nation, 
                             labels = nation_labels)) %>%
    mutate(group = "US Population") %>%
    full_join(sample_nation) %>%
    mutate(race_cat = factor(race_cat, levels = nation_labels, 
                           labels = nation_labels_breaks)) %>%
  filter(!is.na(region)) %>%
  ggplot(aes(x = race_cat, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 5), 
            position = position_dodge(1), size= 2) +
  facet_wrap(~region, scales = "free") +
  labs(x = "", fill = "")+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_minimal(base_size = 8)+
  theme(legend.position = "top") 
```

### Ethnicity by region

```{r, out.width='100%'}

sample_nation = scored_first %>%
  filter(!is.na(latinx) & !is.na(region)) %>%
  group_by(latinx, region) %>%
  summarize(Count = n()) %>%
  group_by(region) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID") %>%
  filter(latinx == 1)

pop %>%
  filter(!is.na(region)) %>%
  select(region, TotalPop.Count, 
         (contains("Race") & contains("Count"))) %>%
  gather(demo, count, -region) %>%
    group_by(region, demo) %>%
    summarize(count = sum(count)) %>%
    spread(demo, count) %>%
    mutate(Percent = 100*Race.Hispanic.Count/TotalPop.Count) %>%
    select(region, contains("Percent")) %>%
    mutate(group = "US Population") %>%
    full_join(sample_nation) %>%
  ggplot(aes(x = region, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 2), 
            position = position_dodge(1), size= 2) +
  labs(x = "", fill = "", 
       title = "Representation of Hispanic/Latinx Caregivers by region")+
  theme_minimal(base_size = 8)+
  theme(legend.position = "top") 
```

# Numbers by the week

```{r, results = 'asis'}
scored %>%
  filter(Week > 0) %>%
  select(Week, all_of(binary_demos)) %>%
  gather("Demographic", value, -Week) %>%
  group_by(Week, Demographic) %>%
  summarize(Count = sum(value,na.rm=T)) %>%
  mutate(Demographic = factor(Demographic, 
                              levels = binary_demos, 
                              labels = binary_labels)) %>%
  ungroup() %>%
  spread("Week", "Count") %>%
  kable(., col.names = c("Demographic", all_dates)) %>%
  kable_styling() %>%
  scroll_box(width = "650px")
```



## Income

```{r, results = 'asis'}
scored %>%
  filter(Week > 0) %>%
  select(Week, income) %>%
  filter(!is.na(income)) %>%
  group_by(Week) %>%
  summarize(Mean = mean(income),
            Median = median(income),
            Bottom10 = quantile(income, probs = c(.10)),
            Top10 = quantile(income, probs = c(.90))) %>%
  kable(., col.names = c("Week", "Average", "Median", "Lowest 10%", "Top 10%")) %>%
  kable_styling()
```


```{r, results = 'asis'}
tab.inc = scored %>%
  filter(Week > 0) %>%
  group_by(CaregiverID) %>%
  filter(Week>0) %>%
  ungroup() %>%
  filter(!is.na(income)) %>%
  mutate(income_cat = income_levels(income, num_levels = 25)) %>%
  group_by(Week, income_cat) %>%
  summarize(Count = n()) %>%
  ungroup() %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  gather("stat","value", Count, Percent) %>%
  mutate(stat = paste0("Week", Week,"_",stat)) %>%
  select(-Week) %>%
  spread(stat,value) 

beginning = "tab.inc %>% kable(., format = \"html\", col.names = c(\"Income (in thounsands per year)\", rep(c(\"Count\", \"Percent\"), max_weeks)), digits = c(0, rep(c(0,1), max_weeks))) %>% kable_styling() %>%"

header = paste0(",\"Week ", 1:max_weeks, "\" = 2", collapse = "")

header = paste0("add_header_above( c( \" \" = 1", header, ")) %>% scroll_box(width = \"650px\")")

eval(parse(text = paste0(beginning, header)))
```

```{r}
ts_income = scored %>%
  filter(Week > 0) %>%
  group_by(CaregiverID) %>%
  filter(Week>0) %>%
  ungroup() %>%
  filter(!is.na(income)) %>%
  mutate(income_cat = income_levels(income, num_levels = 25)) %>%
  group_by(Week, income_cat) %>%
  summarize(Count = n()) %>%
  ungroup() %>%
  mutate(Percent = 100*Count/sum(Count)) 

ts_income <- as_tsibble(ts_income,
                      index = Week,
                      key = income_cat,
                      regular = FALSE)

ts_income %>%
  ggplot(aes(x = Week, y = Percent, color = income_cat)) +
  geom_line() +
  facet_wrap(~income_facet) +
  facet_strata(n_strata = 6, along = income_cat) +
  labs(color = "Yearly income (in thousands)")+
  theme_minimal() +
  theme(legend.position = "bottom")
```



## Healthcare

```{r, results = 'asis'}
source(here("Scripts/health variables.R"))
tab.hc = scored %>%
  filter(Week > 0) %>%
  select(Week, healthcare_vars) %>%
  gather("variable", "value", -Week) %>%
  group_by(Week, variable) %>% 
  filter(!is.na(value)) %>%
  summarize(Count = sum(value), n = n()) %>%
  ungroup() %>%
  mutate(Percent = 100*Count/n) %>%
  select(-n) %>%
  gather("stat","value", Count, Percent) %>%
  mutate(stat = paste0("Week", Week,"_",stat)) %>%
  select(-Week) %>%
  spread(stat,value) 

beginning = "tab.hc %>% kable(., format = \"html\", col.names = c(\"Income (in thounsands per year)\", rep(c(\"Count\", \"Percent\"), max_weeks)), digits = c(0, rep(c(0,1), max_weeks))) %>% kable_styling() %>%"

header = paste0(",\"Week ", 1:max_weeks, "\" = 2", collapse = "")

header = paste0("add_header_above( c( \" \" = 1", header, ")) %>% scroll_box(width = \"650px\")")

eval(parse(text = paste0(beginning, header)))
```

```{r}
scored %>%
  filter(Week > 0) %>%
  select(Week, healthcare_vars) %>%
  gather("variable", "value", -Week) %>%
  group_by(Week, variable) %>% 
  filter(!is.na(value)) %>%
  summarize(Count = sum(value), n = n()) %>%
  ungroup() %>%
  mutate(Percent = 100*Count/n,
         variable = factor(variable, levels = healthcare_vars, labels = healthcare_labels)) %>%
  ggplot(aes(x = Week, y = Percent, color = variable)) +
  geom_line()
```

# Percentages by the week

```{r, results = 'asis'}
total = scored %>%
  filter(Week > 0) %>%
  group_by(Week) %>%
  summarize(Total = n())

scored %>%
  filter(Week > 0) %>%
  select(Week, all_of(binary_demos)) %>%
  gather("Demographic", value, -Week) %>%
  group_by(Week, Demographic) %>%
  summarize(Count = sum(value,na.rm=T)) %>%
  mutate(Demographic = factor(Demographic, 
                              levels = binary_demos, 
                              labels = binary_labels)) %>%
  ungroup() %>%
  full_join(total) %>%
  mutate(Count = 100*Count/Total) %>%
  select(-Total) %>%
  spread("Week", "Count") %>%
  kable(., col.names = c("Demographic", all_dates), digits = 1) %>%
  kable_styling() %>%
  scroll_box(width = "650px")
```