---
title: "Material Hardship Trend"
author: "Sihong"
date: "2/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include = FALSE}
library(here)
library(knitr)
library(readr)
library(haven)
library(tidyverse)
```


```{r, echo=FALSE, message = FALSE}
#Define functions
moe.p = function(p, n){
  q = 1-p
  moe = 1.96*sqrt((p*q)/n)
  return(moe)
}

moe.m = function(sd,n){
  moe = 1.96*sd/sqrt(n)
  return(moe)}

combine.cat = function(x, cols, id, newvar.name){
  subset = x[,c(id, "Week", cols)]
  names(subset) = c("id", "Week", paste0("X",1:length(cols)))
  subset = suppressWarnings(gather(subset, "key", "value", -id, -Week))
  subset = filter(subset, !is.na(value))
  subset$key = gsub("X", "", subset$key)
  subset = group_by(subset, id, Week)
  subset = summarise(subset, newvar = paste(key, collapse = ",")) %>% ungroup()
  names(subset) = c(id,"Week", newvar.name)
  x = suppressMessages(full_join(x, subset))
  return(x)
}

find_items = function(string, data2){
  items = names(data2)
  locations = which(grepl(string, items))
  final = items[locations]
  return(final)
}

my.max = function(x) ifelse (!all(is.na(x)), max(x,na.rm = TRUE), NA)
my.min = function(x) ifelse (!all(is.na(x)), min(x,na.rm = TRUE), NA)
```

```{r, echo=FALSE, message = FALSE, warning = FALSE, include=FALSE}
#OR load master data file
master <- read_sav(here("../../Data Management R3/CC_Clean Survey Data/00_R3 MasterFile/MasterFile_groupings.sav"))

# Remove cases should be excluded
master <- master %>%
  filter ( CaregiverID != "" & is.na(Exclude) == T )

master = master %>%
  group_by(CaregiverID, Week) %>%
  filter(row_number() == max(row_number())) %>%
  ungroup()

total_week <- my.max(master$Week)

#master = master %>%
#  mutate(
#    Week = case_when(
#      Week < 17 ~ Week,
#      Week %% 2 == 0 ~ NA_real_,
#      TRUE ~ Week)
#  ) %>%
#  filter(!is.na(Week))

```

```{r, echo=FALSE, message = FALSE, warning = FALSE}
#Code demographics
master <- master %>%
  mutate (month = case_when(
                  Week == 0 ~ "Pre-COVID",
                  Week >0 & Week <= 4 ~ "April",
                  Week >=5 & Week <=8 ~ "May",
                  Week >=9 & Week <=13 ~ "June",
                  Week >=14 & Week <=17 ~ "July",
                  Week >=18 & Week <=21 ~ "August",
                  Week >=22 & Week <=26 ~ "September",
                  Week >=27 ~ "October"), 
           baseline = case_when (Week - BaselineWeek == 1 ~ 1, 
                                 Week - BaselineWeek > 1 ~ 0))

##Race/ethnicity - 1 = black, 2 = latinx, 3 = white

master <- master %>%
  mutate (RaceGroup = na_if (RaceGroup, 99))%>%
    mutate(
      minority = ifelse(RaceGroup != 5, 1, 0),
      black = ifelse(RaceGroup == 3, 1, 0),
      native = ifelse(RaceGroup == 1, 1, 0),
      asian = ifelse(RaceGroup == 2, 1, 0),
      hawaii = ifelse(RaceGroup == 4, 1, 0),
      white = ifelse(RaceGroup == 5, 1, 0),
      other_race = ifelse(RaceGroup %in% c(6, 7), 1, 0))

master <- master %>%
      mutate(latinx = case_when(
        DEMO.008 == 1 ~ 1,
        DEMO.008 == 0 ~ 0,
        DEMO.008.2 == 0 ~ 0,
        DEMO.008.2 == 1 ~ 1,
        DEMO.008.2 == 2 ~ 1,
        TRUE ~ NA_real_))

master <- master %>%
mutate (race_ethnic = case_when(
      black == 1 ~ "1",
      latinx == 1 ~ "2",
      !is.na(black) ~ "3",
      !is.na(latinx) ~ "3",
      TRUE ~ NA_character_))  

##Povertyline - 0 = high income, 1 = low income
master <- master %>%
  mutate (poverty_cat = FPL.2019.UM.150)

#Material hardship
master <- master %>%
  combine.cat(cols = find_items("FSTR.002_.{1}$", master), 
              id = "CaregiverID",
              newvar.name = "FSTR.002_cat")
  

master <- master %>%
  mutate (diff_pay_food = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("1", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_), 
          diff_pay_utilities = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("3", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_house = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("2", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_healthcare = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("4", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_social = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("5", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_emotional = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("6", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_childcare = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("7", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_other = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("8", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_))

master <- master %>%
  rowwise() %>%
  mutate(material_hardship = case_when(
    Week == 0 ~ NA_real_,
    TRUE ~ sum(c_across(starts_with("diff_pay_")), na.rm=T))) %>%
  ungroup() %>%
  mutate(num_hardship = material_hardship,
    material_hardship = ifelse(material_hardship > 0, 1, 0)) 

## Children with special needs
master <- combine.cat(x = master, 
                       cols = find_items("HEALTH.005_[0-9]{1}$", master), 
                       id = "CaregiverID",
                       newvar.name = "HEALTH.005_cat")
master <- master %>%
   mutate (disability = case_when (HEALTH.005_1 == 1 ~ 1,
                                   HEALTH.005_2 == 1 ~ 1,
                                   HEALTH.005_3 == 1 ~ 1,
                                   HEALTH.005_4 == 1 ~ 1,
                                   HEALTH.005_5 == 1 ~ 0,
                                   HEALTH.005_6 == 1 ~ 1,
                                   TRUE ~ NA_real_))


## Single parent status
master <- master %>%
  mutate (single = case_when (
                   DEMO.002 %in% c(3,4,5,7,8)~1, 
                   DEMO.011 %in% c(2,4)~1,
                   !is.na(DEMO.002)~0,
                   !is.na(DEMO.011)~0,
                   TRUE ~ NA_real_))
                     
## Employment status
master <- combine.cat (x = master,
                       cols = find_items ("JOB.010_.{1,2}$", master), 
                       id = "CaregiverID",
                       newvar.name = "JOB.010_cat")
  
master$JOB.010_cat = gsub("10", "0", master$JOB.010_cat)
master$working_pre = ifelse (grepl("[1,2,6]", master$JOB.010_cat), 1, 0)
master = combine.cat (x = master,
                       cols = find_items ("JOB.008_.{1,2}$", master), 
                       id = "CaregiverID",
                       newvar.name = "JOB.008_cat")
master$JOB.008_cat = gsub("10", "0", master$JOB.008_cat)
master <- master %>%
  mutate (work_status = case_when(
                        grepl ("1", JOB.008_cat) ~ "1", 
                        grepl ("2", JOB.008_cat) ~ "1", 
                        grepl ("3", JOB.008_cat) ~ "0", 
                        grepl ("4", JOB.008_cat) ~ "0", 
                        grepl ("5", JOB.008_cat) ~ "1", 
                        JOB.008.2 == 1 ~ "1",
                        JOB.008.2 %in% c(2,3) ~ "0",
                        TRUE~NA_character_),
          work_status_pre = case_when(
                        grepl ("1", JOB.010_cat) ~ "1", 
                        grepl ("2", JOB.010_cat) ~ "1", 
                        grepl ("3", JOB.010_cat) ~ "0", 
                        grepl ("4", JOB.010_cat) ~ "0", 
                        grepl ("5", JOB.010_cat) ~ "1", 
                        TRUE~NA_character_))
#1 = stable employed 2 = became unemployed 3 = became employed4 = stable unemployed

# Region
master <- master %>%
  mutate (region = na_if (DEMO.001.b, 5))

master_dem <- master %>%
  group_by (CaregiverID) %>%
  summarise (BaselineWeek = my.max (BaselineWeek),
             race_ethnic = my.max(race_ethnic),
             poverty_cat = my.max(poverty_cat),
             material_hardship = my.max(material_hardship),
             disability = my.max (disability),
             single = my.max (single),
             work_status = my.max (work_status),
             work_status_pre = my.max (work_status_pre), 
             region = my.max(region))%>%
  mutate ( ep_change = case_when(
                        work_status == 1 & work_status_pre == 1 ~ "1", 
                        work_status == 1 & work_status_pre == 0 ~ "2", 
                        work_status == 0 & work_status_pre == 1 ~ "3", 
                        work_status == 0 & work_status_pre == 0 ~ "4", 
                        TRUE~NA_character_))%>%
  mutate (race_ethnic = case_when (
                        race_ethnic == 1 ~ "Black", 
                        race_ethnic == 2 ~ "Latinx", 
                        race_ethnic == 3 ~ "White", 
                        TRUE~NA_character_),
          poverty_cat = case_when (
                        poverty_cat == 1 ~ "Low income", 
                        poverty_cat == 0 ~ "High income", 
                        TRUE~NA_character_),
          material_hardship = case_when (
                        material_hardship == 1 ~ "With material hardship", 
                        material_hardship == 0 ~ "Without material hardship", 
                        TRUE~NA_character_),
          disability = case_when (
                        disability == 1 ~ "With disability", 
                        disability == 0 ~ "Without disability", 
                        TRUE~NA_character_),
          single = case_when (
                        single == 1 ~ "Single parent", 
                        single == 0 ~ "Dual parent", 
                        TRUE~NA_character_),
          work_status = case_when (
                        work_status == 1 ~ "Employed", 
                        work_status == 0 ~ "Unemployed", 
                        TRUE~NA_character_),
          work_status_pre = case_when (
                        work_status_pre == 1 ~ "Employed", 
                        work_status_pre == 0 ~ "Unemployed", 
                        TRUE~NA_character_),
          ep_change = case_when (
                        ep_change == 1 ~ "Stable employed", 
                        ep_change == 2 ~ "Became employed", 
                        ep_change == 3 ~ "Became unemployed",
                        ep_change == 4 ~ "Stable unemployed",
                        TRUE~NA_character_), 
          region = case_when (
                        region == 1 ~ "Northeast", 
                        region == 2 ~ "Midwest", 
                        region == 3 ~ "South", 
                        region == 4 ~ "West",
                        TRUE~NA_character_))

```

```{r, echo=FALSE, message = FALSE, warning = FALSE}
# Extract Relevant Variables
##RL questions - online learning

fs <- master %>%
  select (CaregiverID, StartDate, SurveyType,Week, baseline, FSTR.001, contains ("FSTR.002") )%>%
  filter (is.na(Week) == F)
  
fs <- merge (x = master_dem, y = fs,  by.x = "CaregiverID", by.y = "CaregiverID", all.y = T)%>%
 mutate (fs_food = FSTR.002_1, 
         fs_housing = FSTR.002_2, 
         fs_utility = FSTR.002_3, 
         fs_any = ifelse (fs_food == 1 | fs_housing == 1 | fs_utility == 1 , 1, 0))

fs_fl <- fs %>%
  filter (SurveyType == 2)

date <- fs %>%
  group_by (Week)%>%
  summarise (date = min (StartDate))%>%
  ungroup()

num_responses = function(x){length(which(!is.na(x)))}
fs.num <- fs %>%
  group_by(Week) %>%
  summarize_all(num_responses) %>%
  gather("Variable", "num_responses",-Week) %>%
  mutate(week = paste0("Week", Week),
         week = factor(Week, levels = paste0("Week", c(1:total_week)))) %>%
  spread(Week, num_responses)

```

# 1. Overall
```{r, echo=FALSE, message = FALSE, warning = FALSE}
fs_trend <- fs_fl %>%
  group_by (Week)%>%
  summarise (n = n(),
             a.food = sum (fs_food, na.rm = T)/n, 
             b.housing = sum (fs_housing, na.rm = T)/n, 
             c.utility = sum (fs_utility, na.rm = T)/n, 
             d.any_of_three = sum (fs_any, na.rm = T)/n,
             date = as.Date(min (StartDate)))%>%
  pivot_longer (cols = c("a.food", "b.housing", "c.utility", "d.any_of_three"), names_to = "type", values_to = "prop")%>%
  mutate (count = prop * n, 
          moe = map2_dbl(prop, n, moe.p), 
          ci_low = prop-moe,
          ci_high = prop+moe)

fs_trend %>%
  ggplot(mapping = aes (x = date, y = prop*100, fill = type)) +
  geom_point(stat = 'summary') +
  geom_ribbon(aes(ymin = ci_low*100, ymax = ci_high*100), alpha = .3) +
  geom_line() +
  #geom_text(aes(label = round(prop*100,2)),vjust = -2, size = 2.5, color = "black",  position = position_dodge(1))+
  labs (y = "Percentage")+
  scale_x_date (date_breaks = "2 month", date_labels ="%b %Y")+
  facet_wrap (~type, nrow = 2)+ 
  theme(axis.text.x = element_text(angle = 90))

```

# 2. By race/ethnicity
```{r, echo=FALSE, message = FALSE, warning = FALSE}
fs_trend <- fs_fl %>%
  filter (race_ethnic != "NA")%>%
  group_by (Week, race_ethnic)%>%
  summarise (n = n(),
             a.food = sum (fs_food, na.rm = T)/n, 
             b.housing = sum (fs_housing, na.rm = T)/n, 
             c.utility = sum (fs_utility, na.rm = T)/n, 
             d.any_of_three = sum (fs_any, na.rm = T)/n,
             date = as.Date(min (StartDate)))%>%
  pivot_longer (cols = c("a.food", "b.housing", "c.utility", "d.any_of_three"), names_to = "type", values_to = "prop")%>%
  mutate (count = prop * n, 
          moe = map2_dbl(prop, n, moe.p), 
          ci_low = prop-moe,
          ci_high = prop+moe)

fs_trend %>%
  ggplot(mapping = aes (x = date, y = prop*100, fill = race_ethnic)) +
  #geom_point(stat = 'summary') +
  geom_ribbon(aes(ymin = ci_low*100, ymax = ci_high*100), alpha = .3) +
  geom_line() +
  #geom_text(aes(label = round(prop*100,2)),vjust = -2, size = 2.5, color = "black",  position = position_dodge(1))+
  labs (y = "Percentage")+
  scale_x_date (date_breaks = "2 month", date_labels ="%b %Y")+
  facet_wrap (~type, nrow = 2)+ 
  theme(axis.text.x = element_text(angle = 90))

```

# 3. By poverty level
```{r, echo=FALSE, message = FALSE, warning = FALSE}
fs_trend <- fs_fl %>%
  filter (poverty_cat != "NA")%>%
  group_by (Week, poverty_cat)%>%
  summarise (n = n(),
             a.food = sum (fs_food, na.rm = T)/n, 
             b.housing = sum (fs_housing, na.rm = T)/n, 
             c.utility = sum (fs_utility, na.rm = T)/n, 
             d.any_of_three = sum (fs_any, na.rm = T)/n,
             date = as.Date(min (StartDate)))%>%
  pivot_longer (cols = c("a.food", "b.housing", "c.utility", "d.any_of_three"), names_to = "type", values_to = "prop")%>%
  mutate (count = prop * n, 
          moe = map2_dbl(prop, n, moe.p), 
          ci_low = prop-moe,
          ci_high = prop+moe)

fs_trend %>%
  ggplot(mapping = aes (x = date, y = prop*100, fill = poverty_cat)) +
  #geom_point(stat = 'summary') +
  geom_ribbon(aes(ymin = ci_low*100, ymax = ci_high*100), alpha = .3) +
  geom_line() +
  #geom_text(aes(label = round(prop*100,2)),vjust = -2, size = 2.5, color = "black",  position = position_dodge(1))+
  labs (y = "Percentage")+
  scale_x_date (date_breaks = "2 month", date_labels ="%b %Y")+
  facet_wrap (~type, nrow = 2)+ 
  theme(axis.text.x = element_text(angle = 90))

```

# 3. By poverty level & race/ethnicity
```{r, echo=FALSE, message = FALSE, warning = FALSE}
fs_trend <- fs_fl %>%
  filter (poverty_cat != "NA" & race_ethnic != "NA")%>%
  group_by (Week, poverty_cat, race_ethnic)%>%
  summarise (n = n(),
             a.food = sum (fs_food, na.rm = T)/n, 
             b.housing = sum (fs_housing, na.rm = T)/n, 
             c.utility = sum (fs_utility, na.rm = T)/n, 
             d.any_of_three = sum (fs_any, na.rm = T)/n,
             date = as.Date(min (StartDate)))%>%
  pivot_longer (cols = c("a.food", "b.housing", "c.utility", "d.any_of_three"), names_to = "type", values_to = "prop")%>%
  mutate (count = prop * n, 
          moe = map2_dbl(prop, n, moe.p), 
          ci_low = prop-moe,
          ci_high = prop+moe)

fs_trend %>%
  ggplot(mapping = aes (x = date, y = prop*100, fill = poverty_cat)) +
  #geom_point(stat = 'summary') +
  geom_ribbon(aes(ymin = ci_low*100, ymax = ci_high*100), alpha = .3) +
  geom_line() +
  #geom_text(aes(label = round(prop*100,2)),vjust = -2, size = 2.5, color = "black",  position = position_dodge(1))+
  labs (y = "Percentage")+
  scale_x_date (date_breaks = "2 month", date_labels ="%b %Y")+
  facet_wrap (race_ethnic~type, nrow = 3)+ 
  theme(axis.text.x = element_text(angle = 90))

```
