---
title: "Open-ended childcare responses"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r chunk 1, echo = F}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '')

num_topics = 33
```

```{r packages}
library(here)
library(stm)
library(tidytext)
library(furrr)
library(ggpubr)
library(psych)
library(conflicted)
library(LDAvis)
library(tidystm)
library(ggrepel)
```

```{r}
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
source(here("Scripts/score data.R")) 
source(here("Functions/pomp.R"))
conflict_prefer("map", "purrr")

```

```{r prep open-ended responses for tokenizing}
open_ended = scored %>%
  filter(language != "ES") %>%
  filter(language != "SPA") %>%
  select(-contains("OPEN.006")) %>%
  filter(!is.na(race_ethnic)) %>%
  filter(!is.na(poverty_cat)) %>%
  filter(!is.na(mental_health)) %>%
  gather("question", "response", contains("OPEN")) %>%
  mutate(question = str_extract(question, ".$")) %>%
  filter(!is.na(response)) 

#identify question about childcare
open_ended = open_ended %>%
  mutate(about_childcare = case_when(
    str_detect(response, "childcare") ~ 1,
    str_detect(response, "child care") ~ 1,
    str_detect(response, "daycare") ~ 1,
    str_detect(response, "day care") ~ 1,
    str_detect(response, "nanny") ~ 1,
    str_detect(response, "babysitter") ~ 1,
    str_detect(response, "baby sitter") ~ 1,
    str_detect(response, "care center") ~ 1,
    str_detect(response, "child care") ~ 1,
    str_detect(response, "playgroup") ~ 1,
    str_detect(response, "play group") ~ 1,
    str_detect(response, "class") ~ 1,
    TRUE ~ NA_real_
  )) %>%
  filter(about_childcare == 1)
```

## How many topics

```{r prep q1, results='hide'}
processed1 <- textProcessor(open_ended$response, metadata = open_ended)
out1 <- prepDocuments(processed1$documents, processed1$vocab, processed1$meta)
docs1 <- out1$documents
vocab1 <- out1$vocab
meta1 <- out1$meta

heldout1 = make.heldout(docs1, vocab1)
```

```{r models q1, eval = F}

set.seed(07312020)
plan(multiprocess)

many_models <- tibble(K =seq(5,150, by=5)) %>%
  mutate(topic_model = future_map(K, ~stm(heldout1$documents, 
                                          heldout1$vocab, 
                                          K = .,
                                          prevalence =~ question + race_ethnic + poverty150 + mental_health + s(Week),
                                          data = meta1, 
                                          verbose = FALSE)))
k_result <- many_models %>%
  mutate(exclusivity = map(topic_model, exclusivity),
         semantic_coherence = map(topic_model, semanticCoherence, heldout1$documents),
         eval_heldout = map(topic_model, eval.heldout, heldout1$missing),
         residual = map(topic_model, checkResiduals, heldout1$documents),
         bound =  map_dbl(topic_model, function(x) max(x$convergence$bound)),
         lfact = map_dbl(topic_model, function(x) lfactorial(x$settings$dim$K)),
         lbound = bound + lfact,
         iterations = map_dbl(topic_model, function(x) length(x$convergence$bound)))

save(many_models, k_result, file = here("../../Data Management R3/R Data/openchild_many_models.Rdata"))
```

```{r, eval = F}
load(here("../../Data Management R3/R Data/openchild_many_models.Rdata"))

```

```{r, eval = F}
k_result %>%
  transmute(K,
            `Lower bound` = lbound,
            Residuals = map_dbl(residual, "dispersion"),
            `Semantic coherence` = map_dbl(semantic_coherence, mean),
            `Held-out likelihood` = map_dbl(eval_heldout, "expected.heldout")) %>%
  gather(Metric, Value, -K) %>%
  ggplot(aes(K, Value, color = Metric)) +
  geom_line(size = 1.5, alpha = 0.7, show.legend = FALSE) +
  facet_wrap(~Metric, scales = "free_y") +
  scale_x_continuous(breaks = seq(0,150,10))+
  labs(x = "K (number of topics)",
       y = NULL,
       title = "Model diagnostics by number of topics") +
  theme_pubclean()
```

```{r, eval = F}
findingK = searchK(out1$documents, out1$vocab, K = c(30:50), prevalence =~ question + race_ethnic + poverty150 + mental_health + s(Week), data = meta1, proportion = .5, verbose = F)
```

```{r, eval=FALSE, include=FALSE}
set.seed(07312020)
plan(multiprocess)

many_models <- tibble(K =c(32:37, 49:53)) %>%
  mutate(topic_model = future_map(K, ~stm(heldout1$documents, 
                                          heldout1$vocab, 
                                          K = .,
                                          prevalence =~ question + race_ethnic + poverty150 + mental_health + s(Week),
                                          data = meta1, 
                                          verbose = FALSE)))
k_result <- many_models %>%
  mutate(exclusivity = map(topic_model, exclusivity),
         semantic_coherence = map(topic_model, semanticCoherence, heldout1$documents),
         eval_heldout = map(topic_model, eval.heldout, heldout1$missing),
         residual = map(topic_model, checkResiduals, heldout1$documents),
         bound =  map_dbl(topic_model, function(x) max(x$convergence$bound)),
         lfact = map_dbl(topic_model, function(x) lfactorial(x$settings$dim$K)),
         lbound = bound + lfact,
         iterations = map_dbl(topic_model, function(x) length(x$convergence$bound)))

save(many_models, k_result, file = here("../../Data Management R3/R Data/openchild_many_models2.Rdata"))

```

```{r, eval = F}
k_result %>%
  transmute(K,
            `Lower bound` = lbound,
            Residuals = map_dbl(residual, "dispersion"),
            `Semantic coherence` = map_dbl(semantic_coherence, mean),
            `Held-out likelihood` = map_dbl(eval_heldout, "expected.heldout")) %>%
  gather(Metric, Value, -K) %>%
  ggplot(aes(K, Value, color = Metric)) +
  geom_point()+
  geom_line()+
  facet_wrap(~Metric, scales = "free_y") +
  labs(x = "K (number of topics)",
       y = NULL,
       title = "Model diagnostics by number of topics") +
  theme_pubclean()
```

```{r, eval = F}
stm_child36 <- stm(documents = docs1, 
                    vocab = vocab1,
                    K = 36, 
                    prevalence =~ question + race_ethnic + poverty150 + mental_health + s(Week),
                    data = meta1, 
                    init.type = "Spectral")

save(stm_child, file = here("../../Data Management R3/R Data/open_child_model.Rdata"))
```

```{r}
load(file = here("../../Data Management R3/R Data/topics_child.Rdata"))
topics_child = get(paste0("stm_child", num_topics))
```

```{r, eval = F}
# assess structure visually
toLDAvis(stm_child33, docs = docs1)
```

## Most common topics

```{r}
td_beta1 <- tidy(topics_child)
td_gamma1 <- tidy(topics_child, matrix = "gamma")

meta1 = meta1 %>%
  mutate(document = row_number())


top_terms <- td_beta1 %>%
  arrange(beta) %>%
  group_by(topic) %>%
  top_n(7, beta) %>%
  arrange(-beta) %>%
  select(topic, term) %>%
  summarise(terms = list(term)) %>%
  mutate(terms = map(terms, paste, collapse = ", ")) %>%
  unnest(cols = c(terms))

gamma_terms <- td_gamma1 %>%
  group_by(topic) %>%
  summarise(gamma = mean(gamma)) %>%
  arrange(desc(gamma)) %>%
  left_join(top_terms, by = "topic") %>%
  mutate(topic = paste0("Topic ", topic),
         topic = reorder(topic, gamma))

gamma_terms %>%
  top_n(15, gamma) %>%
  ggplot(aes(topic, gamma, label = terms, fill = topic)) +
  geom_col(show.legend = FALSE) +
  geom_text(hjust = 0, nudge_y = 0.0005, size = 3) +
  #scale_y_continuous(limits =c(0, .10))+
  coord_flip() +
  #theme_tufte(base_family = "IBMPlexSans", ticks = FALSE) +
  labs(x = NULL, y = expression(gamma),
       title = "Top 15 topics by prevalence response",
       subtitle = "With the top words that contribute to each topic") +
  theme_pubr()
```

## Identify topics {.tabset}

### All

### 1

```{r}
texts = open_ended$response[-out1$docs.removed]
labelTopics(topics_child, topics = 1, n = 5)
findThoughts(topics_child, texts, topics = 1, n = 5)
```

### 2

```{r}
labelTopics(topics_child, topics = 2, n = 5)
findThoughts(topics_child, texts, topics = 2, n = 5)
```

### 3

```{r}
labelTopics(topics_child, topics = 3, n = 5)
findThoughts(topics_child, texts, topics = 3, n = 5)
```

### 4

```{r}
labelTopics(topics_child, topics = 4, n = 5)
findThoughts(topics_child, texts, topics = 4, n = 5)
```

### 5

```{r}
labelTopics(topics_child, topics = 5, n = 5)
findThoughts(topics_child, texts, topics = 5, n = 5)
```

### 6

```{r}
labelTopics(topics_child, topics = 6, n = 5)
findThoughts(topics_child, texts, topics = 6, n = 5)
```

### 7

```{r}
labelTopics(topics_child, topics = 7, n = 5)
findThoughts(topics_child, texts, topics = 7, n = 5)
```

### 8

```{r}
labelTopics(topics_child, topics = 8, n = 5)
findThoughts(topics_child, texts, topics = 8, n = 5)
```

### 9

```{r}
tx = 9
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 10

```{r}
tx = 10
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 11

```{r}
tx = 11
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 12

```{r}
tx = 12
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 13

```{r}
tx = 13
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 14

```{r}
tx = 14
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 15

```{r}
tx = 15
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 16

```{r}
tx = 16
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 17

```{r}
tx = 17
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 18

```{r}
tx = 18
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 19

```{r}
tx = 19
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 20

```{r}
tx = 20
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 21

```{r}
tx = 21
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 22

```{r}
tx = 22
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 23

```{r}
tx = 23
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 24

```{r}
tx = 24
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 25

```{r}
tx = 25
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 26

```{r}
tx = 26
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 27

```{r}
tx = 27
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 28

```{r}
tx = 28
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 29

```{r}
tx = 29
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 30

```{r}
tx = 30
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 31

```{r}
tx = 31
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 32

```{r}
tx = 32
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

### 33

```{r}
tx = 33
labelTopics(topics_child, topics = tx, n = 5)
findThoughts(topics_child, texts, topics = tx, n = 5)
```

<!-- ### 34 -->

<!-- ```{r} -->
<!-- tx = 34 -->
<!-- labelTopics(topics_child, topics = tx, n = 5) -->
<!-- findThoughts(topics_child, texts, topics = tx, n = 5) -->
<!-- ``` -->

<!-- ### 35 -->

<!-- ```{r} -->
<!-- tx = 35 -->
<!-- labelTopics(topics_child, topics = tx, n = 5) -->
<!-- findThoughts(topics_child, texts, topics = tx, n = 5) -->
<!-- ``` -->

<!-- ### 36 -->

<!-- ```{r} -->
<!-- tx = 36 -->
<!-- labelTopics(topics_child, topics = tx, n = 5) -->
<!-- findThoughts(topics_child, texts, topics = tx, n = 5) -->
<!-- ``` -->

<!-- ## Topics by demographic{.tabset} -->

<!-- ### Black/African American -->

<!-- ```{r} -->

<!-- gamma_terms <- td_gamma1 %>% -->

<!--   full_join(meta1) %>% -->

<!--   group_by(topic, black) %>% -->

<!--   summarise(gamma = mean(gamma)) %>% -->

<!--   arrange(desc(gamma)) %>% -->

<!--   left_join(top_terms, by = "topic") %>% -->

<!--   mutate(topic = paste0("Topic ", topic), -->

<!--          topic = reorder(topic, gamma)) -->

<!-- gamma_terms %>% -->

<!--   group_by(black) %>% -->

<!--   top_n(15, gamma) %>% -->

<!--   mutate(black = factor(black, levels = c(0,1), labels = c("Not Black", "Black"))) %>% -->

<!--   ggplot(aes(reorder(topic,gamma), gamma, label = terms, fill = topic)) + -->

<!--   geom_col(show.legend = FALSE) + -->

<!--   geom_text(hjust = 0, nudge_y = 0.0005, size = 3) + -->

<!--   scale_y_continuous(limits =c(0, .2))+ -->

<!--   coord_flip() + -->

<!--   #theme_tufte(base_family = "IBMPlexSans", ticks = FALSE) + -->

<!--   labs(x = NULL, y = expression(gamma), -->

<!--        title = "Top 15 topics by prevalence response to Q1", -->

<!--        subtitle = "With the top words that contribute to each topic") + -->

<!--   facet_wrap(~black, scales = "free")+ -->

<!--   theme_pubr() -->

<!-- ``` -->

<!-- ```{r} -->

<!-- big_diff = gamma_terms %>% -->

<!--   filter(!is.na(black)) %>% -->

<!--   select(-terms) %>% -->

<!--   spread(black, gamma) %>% -->

<!--   mutate(diff = `1`-`0`) %>% -->

<!--   arrange(desc(abs(diff)))  -->

<!-- gamma_terms %>% -->

<!--   filter(topic %in% big_diff$topic[1:5]) %>% -->

<!--   filter(!is.na(black)) %>% -->

<!--   group_by(black) %>% -->

<!--   top_n(20, gamma) %>% -->

<!--   mutate(black = factor(black, levels = c(0,1), labels = c("Not Black", "Black"))) %>% -->

<!--   ggplot(aes(reorder(topic,gamma), gamma, label = terms, fill = black))+ -->

<!--   geom_col(position = "dodge") + -->

<!--   coord_flip() + -->

<!--   labs(x = NULL, y = expression(gamma), title = "Differences among income groups", fill = NULL)+ -->

<!--   theme_pubr() -->

<!-- ``` -->

<!-- ### Poverty -->

<!-- ```{r} -->

<!-- gamma_terms <- td_gamma1 %>% -->

<!--   full_join(meta1) %>% -->

<!--   group_by(topic, poverty150) %>% -->

<!--   summarise(gamma = mean(gamma)) %>% -->

<!--   arrange(desc(gamma)) %>% -->

<!--   left_join(top_terms, by = "topic") %>% -->

<!--   mutate(topic = paste0("Topic ", topic), -->

<!--          topic = reorder(topic, gamma)) -->

<!-- gamma_terms %>% -->

<!--   filter(!is.na(poverty150)) %>% -->

<!--   group_by(poverty150) %>% -->

<!--   top_n(15, gamma) %>% -->

<!--   mutate(poverty150 = factor(poverty150, levels = c(0,1), labels = c("High Income", "Low Income"))) %>% -->

<!--   ggplot(aes(reorder(topic,gamma), gamma, label = terms, fill = topic)) + -->

<!--   geom_col(show.legend = FALSE) + -->

<!--   geom_text(hjust = 0, nudge_y = 0.0005, size = 3) + -->

<!--   scale_y_continuous(limits =c(0, .2))+ -->

<!--   coord_flip() + -->

<!--   #theme_tufte(base_family = "IBMPlexSans", ticks = FALSE) + -->

<!--   labs(x = NULL, y = expression(gamma), -->

<!--        title = "Top 15 topics by prevalence response to Q1", -->

<!--        subtitle = "With the top words that contribute to each topic") + -->

<!--   facet_wrap(~poverty150, scales = "free")+ -->

<!--   theme_pubr() -->

<!-- ``` -->

<!-- ```{r} -->

<!-- big_diff = gamma_terms %>% -->

<!--   filter(!is.na(poverty150)) %>% -->

<!--   select(-terms) %>% -->

<!--   spread(poverty150, gamma) %>% -->

<!--   mutate(diff = `1`-`0`) %>% -->

<!--   arrange(desc(abs(diff)))  -->

<!-- gamma_terms %>% -->

<!--   filter(topic %in% big_diff$topic[1:5]) %>% -->

<!--   filter(!is.na(poverty150)) %>% -->

<!--   group_by(poverty150) %>% -->

<!--   top_n(20, gamma) %>% -->

<!--   mutate(poverty150 = factor(poverty150, levels = c(0,1),  -->

<!--                              labels = c("High Income", "Low Income"))) %>% -->

<!--   ggplot(aes(reorder(topic,gamma), gamma, label = terms, fill = poverty150))+ -->

<!--   geom_col(position = "dodge") + -->

<!--   coord_flip() + -->

<!--   labs(x = NULL, y = expression(gamma),  -->

<!--        title = "Differences among income groups", fill = NULL)+ -->

<!--   theme_pubr() -->

<!-- ``` -->

<!-- ## Topics by week -->

<!-- ```{r} -->

<!-- library(brolgar) -->

<!-- gamma_terms <- td_gamma1 %>% -->

<!--   full_join(meta1) %>% -->

<!--   group_by(topic, Week) %>% -->

<!--   summarise(gamma = mean(gamma)) %>% -->

<!--   arrange(desc(gamma)) %>% -->

<!--   left_join(top_terms, by = "topic") %>% -->

<!--   mutate(topic = paste0("Topic ", topic), -->

<!--          topic = reorder(topic, gamma)) %>% -->

<!--   ungroup() -->

<!-- gamma_terms = as_tsibble(gamma_terms, -->

<!--                          index = Week,  -->

<!--                          key = topic) -->

<!-- gamma_terms %>% -->

<!--   ggplot(aes(x = Week, y = gamma, color = topic)) + -->

<!--   geom_line() +  -->

<!--   facet_strata(n_strata = 6) + -->

<!--   guides(colour = guide_legend(nrow = 3))+ -->

<!--   #guides(color = F)+ -->

<!--   theme_pubclean() -->

<!-- gamma_terms %>% -->

<!--   #filter(grepl("(2[5-9])|(30)", topic)) %>% -->

<!-- #  filter(grepl("1[1-2]$", topic)) %>% -->

<!--   filter(topic  %in% c("Topic 4", "Topic 9", "Topic 12")) %>% -->

<!--   ggplot(aes(x = Week, y = gamma, color = topic)) + -->

<!--   geom_line() +  -->

<!--   guides(colour = guide_legend(nrow = 1))+ -->

<!--   theme_pubclean() -->

<!-- ``` -->

<!-- ## Topic clusters{.tabset} -->

<!-- ### Topic structure -->

<!-- ```{r} -->

<!-- gamma_terms_wide <- td_gamma1 %>% -->

<!--   full_join(meta1) %>% -->

<!--   mutate(topic = paste0("Topic", topic)) %>% -->

<!--   spread(topic, gamma)  -->

<!-- topics_only_wide = gamma_terms_wide %>% -->

<!--   select(starts_with("Topic")) -->

<!-- iclust(topics_only_wide) -->

<!-- ``` -->

<!-- ### Topic structure (Black respondants only) -->

<!-- ```{r} -->

<!-- gamma_terms_wide <- td_gamma1 %>% -->

<!--   full_join(meta1) %>% -->

<!--   mutate(topic = paste0("Topic", topic)) %>% -->

<!--   spread(topic, gamma)  -->

<!-- topics_only_wide = gamma_terms_wide %>% -->

<!--   filter(black == 1) %>% -->

<!--   select(starts_with("Topic")) -->

<!-- iclust(topics_only_wide) -->

<!-- ``` -->

<!-- ### Cluster 1 -->

<!-- ```{r} -->

<!-- findThoughts(topics_child, texts = out1$meta$response,  -->

<!--              topics = c(17,1,6,24,22,13,4,21), n = 5) -->

<!-- ``` -->

<!-- ### Cluster 2 -->

<!-- ```{r} -->

<!-- findThoughts(topics_child, texts = out1$meta$response,  -->

<!--              topics = c(5, 20, 2, 3, 25, 12, 9, 11), n = 5) -->

<!-- ``` -->

<!-- ### Cluster 3 -->

<!-- ```{r} -->

<!-- findThoughts(topics_child, texts = out1$meta$response,  -->

<!--              topics = c(23,  18, 19, 15, 7), n = 5) -->

<!-- ``` -->

<!-- ### Doublet 1 -->

<!-- ```{r} -->

<!-- findThoughts(topics_child, texts = out1$meta$response,  -->

<!--              topics = c(16, 10), n = 5) -->

<!-- ``` -->

<!-- ### Doublet 2 -->

<!-- ```{r} -->

<!-- findThoughts(topics_child, texts = out1$meta$response,  -->

<!--              topics = c(8, 14), n = 5) -->

<!-- ``` -->

# Effects

```{r}
# extract topic frequencies
td_gamma <- tidy(topics_child, matrix = "gamma")

prob_threshold = .1

topic_freq = td_gamma %>%
  mutate(contains = ifelse(gamma < prob_threshold, 0, 1)) %>%
  group_by(topic) %>%
  summarize(freq = sum(contains))

```


```{r}
predict_topics<-estimateEffect(formula = 1:num_topics ~ question + race_ethnic + poverty150 + mental_health + s(Week), 
                               stmobj = topics_child, 
                               metadata = out1$meta, 
                               uncertainty = "Global")
```

```{r}
race_effect = extract.estimateEffect(predict_topics, covariate = "race_ethnic")
poverty_effect = extract.estimateEffect(predict_topics, covariate = "poverty150")
mental_effect = extract.estimateEffect(predict_topics, covariate = "mental_health")
```

```{r}
race_plot_data = race_effect %>%
  select(topic, covariate.value, estimate) %>%
  spread(covariate.value, estimate)

poverty_plot_data = poverty_effect %>%
  select(topic, covariate.value, estimate) %>%
  spread(covariate.value, estimate) %>%
  mutate(poverty = `0`-`1`)

mental_plot_data = mental_effect %>%
  group_by(topic) %>%
  nest() %>%
  mutate(model = map(data, ~lm(estimate~covariate.value, data = .x))) %>%
  mutate(model = map(model, tidy)) %>%
  select(topic, model) %>%
  unnest(cols = c(model)) %>%
  filter(term == "covariate.value") %>%
  select(topic, estimate)

full_join(race_plot_data, mental_plot_data) %>%
  full_join(topic_freq) %>%
  mutate(BlacktoWhite = White-Black) %>%
  ggplot(aes(x = BlacktoWhite, y = estimate)) +
  geom_point(aes(size = freq), color = "grey") +
  geom_text_repel(aes(label = topic)) +
  scale_x_continuous(NULL, breaks = c(-.015, .02), labels = c("Black", "White")) +
  scale_y_continuous("Mental health problems", breaks = NULL) +
  theme_pubclean() +
  theme(axis.text.x = element_text(size = 18, color = "Black"))
```


```{r}
full_join(poverty_plot_data, mental_plot_data) %>%
  full_join(topic_freq) %>%
  ggplot(aes(x = poverty, y = estimate)) +
  geom_point(aes(size = freq), color = "grey") +
  geom_text_repel(aes(label = topic)) +
  scale_x_continuous(NULL, breaks = c(-.02, .01), 
                     labels = c("Low Income", "High Income")) +
  scale_y_continuous("Mental health problems", breaks = NULL) +
  theme_pubclean() +
  theme(axis.text.x = element_text(size = 18, color = "Black"))
```


