---
title: "Week 6 (May 12 - May 18) Summary"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
  
---

```{r, echo = F}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '')
```

```{r packages}
library(here)
library(haven)
library(tidyverse)
library(knitr)
library(kableExtra)
library(zipcode)
```


```{r score datafile, echo = F, warning = F, message = F}

# source functions --------------------------------------------------------

source(here("Functions/score_report.R"))
source(here("Functions/summarizing_report.R"))


# score master --------------------------------------------------------

source(here("Scripts/score data.R"))

scored = scored %>%
  filter(Week == 6)

```

```{r, key demographics}
source(here("Scripts/demo groups.R"))
```

```{r identify binary variables}
binary_vars = c(
  "access_telehealth",
  "access_social",
  "access_online",
  "increase_familyCC",
  "decrease_familyCC",
  "increase_nonfamilyCC",
  "decrease_nonfamilyCC",
  "parent_edu_interrupt",
  "child_edu_interrupt",
  "insurance",
  "child_insurance",
  "delay_healthcare",
  "suspected_covid",
  "diagnosed_covid",
  "hospital",
  "hospital_covid",
  "anxiety_increase",
  "depress_increase",
  "stress_increase",
  "support_decrease",
  "lone_increase",
  "lost_free_lunch",
  "gained_free_lunch",
  "employment_decreased",
  "sick_leave",
  "losejob_sickleave",
  "unemployment",
  "income_decreaed",
  "financial_prob",
  "major_financial",
  "difficulty_basics",
  "fussy_more",
  "fear_more"
  )

binary_vars_labels = c(
  "Accessed telehealth services",
  "Accessed social/emotional health online",
  "Accessed any online/digital services",
  "Increased hours of family childcare",
  "Decreased hours of family childcare",
  "Increased hours of non-family childcare",
  "Decreased hours of non-family childcare",
  "Parent education interrupted",
  "Child education interrupted",
  "Parent covered by health insurance",
  "Child covered by health insurance",
  "Delayed healthcare for any reason",
  "Suspected of having or diagnosed with COVID-19",
  "Diagnosed with COVID-19",
  "Hospitalized",
  "Hospitalized with COVID-19",
  "Experienced increased anxiety",
  "Experienced increased depression",
  "Experienced increased stress",
  "Experienced decreased support",
  "Experienced increased loneliness",
  "Lost free lunch for child",
  "Gained free lunch for child",
  "Have lower employment status",
  "Has sick leave through employer",
  "Fears losing job if takes 2 weeks of sick leave",
  "Received unemployment benefits",
  "Lost household income",
  "Have some financial problems",
  "Have major financial problems",
  "Have difficulty paying for basic necessicites",
  "Report fussier and more defiant children",
  "Report more fearful children"
  )
```

```{r percentages for all}
perc.all = scored %>%
  select(all_of(binary_vars)) %>%
  summarise_all(percent.report) %>%
  mutate(group_label = "all")
perc.all$N = nrow(scored)
```

```{r percentages by group}
for(i in demos){
  
  new_perc = scored %>%
    select(all_of(i), all_of(binary_vars))
  
  names(new_perc)[1] = "group" 
  
  new_perc_vals = new_perc %>%
    filter(!is.na(group)) %>%
    group_by(group) %>%
    summarise_at(binary_vars, 
                 percent.report)
  new_perc = new_perc %>%
    filter(!is.na(group)) %>%
    group_by(group) %>%
    summarize(N = n()) %>%
    full_join(new_perc_vals) %>%
    ungroup(group) %>%
    mutate(group_label = i) %>%
    mutate(group = as.character(group))
  
  if(i %in% binary_demos){
    new_perc = filter(new_perc, group == "1")
    new_perc$group = NA_character_}
  
  perc.all = suppressMessages(full_join(perc.all, new_perc))
}


```

```{r, results = 'asis'}
#build groupings
group.levels = c("all", binary_demos, setdiff(demos, binary_demos))
group.labels = c("All participants", demo_labels[order(match(demos, group.levels))])

perc.all$group_label = factor(perc.all$group_label, levels = group.levels)
perc.all = arrange(perc.all, group_label)


first.row = sapply(group.levels, first_instance, string = perc.all$group_label)
last.row = sapply(group.levels, last_instance, string = perc.all$group_label)


each_string = paste0("group_rows(group_label = \" ", 
                     group.labels, 
                     "\" , start_row = ", 
                     first.row, 
                     ", end_row = ", 
                     last.row, 
                     ")")
each_string = paste(each_string, collapse = " %>% ")

```

# Summary tables{.tabset .tabset-pills}

## Services and childcare

```{r services table, results="asis"}
services = c(
  "access_telehealth",
  "access_social",
  "access_online",
  "increase_familyCC",
  "decrease_familyCC",
  "increase_nonfamilyCC",
  "decrease_nonfamilyCC"
  )
services_labels = binary_vars_labels[match(services, binary_vars)]

services_beginning= "perc.all %>% select(group, N, services) %>% kable(., col.names = c(\"Group\", \"Sample Size\", services_labels)) %>%
  kable_styling() %>%"

eval(parse(text = paste0(services_beginning, each_string)))
```


## Education

```{r education table, results="asis"}
education = c(
   "parent_edu_interrupt",
  "child_edu_interrupt",
  "lost_free_lunch",
  "gained_free_lunch"
  )
education_labels = binary_vars_labels[match(education, binary_vars)]

education_beginning= "perc.all %>% select(group, N, education) %>% kable(., col.names = c(\"Group\", \"Sample Size\", education_labels)) %>% kable_styling() %>% "

eval(parse(text = paste0(education_beginning, each_string)))
```

## Health

```{r health table, results="asis"}
health = c(
   "insurance",
  "child_insurance",
  "delay_healthcare",
  "suspected_covid",
  "diagnosed_covid",
  "hospital",
  "hospital_covid"
  )
health_labels = binary_vars_labels[match(health, binary_vars)]

health_beginning= "perc.all %>% select(group, N, health) %>% kable(., col.names = c(\"Group\", \"Sample Size\", health_labels)) %>% kable_styling() %>% "

eval(parse(text = paste0(health_beginning, each_string)))
```


## Mental health

```{r mental table, results="asis"}
mental = c(
"anxiety_increase",
  "depress_increase",
  "stress_increase",
  "support_decrease",
  "lone_increase",
  "fussy_more",
  "fear_more"
  )
mental_labels = binary_vars_labels[match(mental, binary_vars)]

mental_beginning= "perc.all %>% select(group, N, mental) %>% kable(., col.names = c(\"Group\", \"Sample Size\", mental_labels)) %>% kable_styling() %>% "

eval(parse(text = paste0(mental_beginning, each_string)))
```

## Financial 

```{r financial table, results="asis"}
financial = c(
"employment_decreased",
  "sick_leave",
  "losejob_sickleave",
  "unemployment",
  "income_decreaed",
  "financial_prob",
  "major_financial",
  "difficulty_basics"
  )
financial_labels = binary_vars_labels[match(financial, binary_vars)]

financial_beginning= "perc.all %>% select(group, N, financial) %>% kable(., col.names = c(\"Group\", \"Sample Size\", financial_labels)) %>% kable_styling() %>% "

eval(parse(text = paste0(financial_beginning, each_string)))
```

# Comparisons with national demographics {.tabset}

```{r}
pop = read_sav(here("../../Data Management R3/CC_Clean Survey Data/00_R3 MasterFile/Population_Estimates.sav"))
pop = pop %>%
  mutate(region = case_when(
    Region == 1 ~ "Northeast",
    Region == 2 ~ "Midwest",
    Region == 3 ~ "South",
    Region == 4 ~ "West"
  ))
```

## Gender

```{r, out.width='100%'}
sample_gender = scored %>%
  filter(!is.na(gender) & !is.na(region)) %>%
  group_by(gender, region) %>%
  summarize(Count = n()) %>%
  group_by(region) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID")

#pop_gender = 
  
pop %>%
    filter(!is.na(region)) %>%
  select(region, TotalPop.Count, Male.Count, Female.Count) %>%
  gather(gender, count, -region) %>%
    group_by(region, gender) %>%
    summarize(count = sum(count)) %>%
    spread(gender, count) %>%
    mutate(Female.Percent = 100*Female.Count/TotalPop.Count,
           Male.Percent = 100*Male.Count/TotalPop.Count,
           Other.Percent = 100*(TotalPop.Count - Female.Count - Male.Count)/TotalPop.Count) %>%
    select(region, contains("Percent")) %>%
    gather("gender", "Percent", contains("Percent")) %>%
    mutate(gender = gsub("\\.Percent", "", gender)) %>%
    mutate(group = "US Population") %>%
    full_join(sample_gender) %>%
  ggplot(aes(x = region, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 5), position = position_dodge(1)) +
  facet_grid(.~gender) +
  labs(x = "", fill = "")+
  theme_minimal(base_size = 10)+
  theme(legend.position = "top")
```

## Nationality

```{r, out.width='100%'}
nation = c(
"native",
"asian",
"black",
"hawaii",
"white",
"other",
"multiple")

nation_labels = c(
"American Indian/Alaska Native",
"Asian",
"Black/African American",
"Native Hawaiian/Pacific Islander",
"White/Caucasian",
"Other race",
"Multiple races")

nation_labels_breaks = c(
"American Indian/\nAlaska Native",
"Asian",
"Black/\nAfrican American",
"Native Hawaiian/\nPacific Islander",
"White\nCaucasian",
"Other\nrace",
"Multiple\nraces")


sample_nation = scored %>%
  filter(!is.na(race_cat))%>%
  group_by(race_cat) %>%
  summarize(Count = n()) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID")

pop %>%
  select(TotalPop.Count, 
         (contains("Race") & contains("Count"))) %>%
  gather(demo, count) %>%
    group_by(demo) %>%
    summarize(count = sum(count)) %>%
    spread(demo, count) %>%
    mutate(native.Percent = 100*Race.Amer.Ind.Count/TotalPop.Count,
           asian.Percent = 100*Race.Asian.Count/TotalPop.Count,
           black.Percent = 100*Race.Black.Count/TotalPop.Count,
           hawaii.Percent = 100*Race.Nat.HI.Count/TotalPop.Count,
           white.Percent = 100*Race.White.Count/TotalPop.Count,
           other.Percent = 100*Race.Other.Count/TotalPop.Count,
           ) %>%
    gather("demo", "Percent", contains("Percent")) %>%
    mutate(demo = gsub("\\.Percent", "", demo),
           race_cat = factor(demo, levels = nation, labels = nation_labels)) %>%
  select(race_cat, Percent) %>%
    mutate(group = "US Population") %>%
    full_join(sample_nation) %>%
  mutate(race_cat = factor(race_cat, 
                           levels = nation_labels, 
                           labels = nation_labels_breaks)) %>%
  ggplot(aes(x = race_cat, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 5), position = position_dodge(1)) +
  labs(x = "", fill = "")+
  theme_minimal(base_size = 10)+
  theme(legend.position = "top") 
```

## Nationality by region

```{r, out.width='100%'}

sample_nation = scored %>%
  filter(!is.na(race_cat) & !is.na(region)) %>%
  group_by(race_cat, region) %>%
  summarize(Count = n()) %>%
  group_by(region) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID")

pop %>%
  filter(!is.na(region)) %>%
  select(region, TotalPop.Count, 
         (contains("Race") & contains("Count"))) %>%
  gather(demo, count, -region) %>%
    group_by(region, demo) %>%
    summarize(count = sum(count)) %>%
    spread(demo, count) %>%
    mutate(native.Percent = 100*Race.Amer.Ind.Count/TotalPop.Count,
           asian.Percent = 100*Race.Asian.Count/TotalPop.Count,
           black.Percent = 100*Race.Black.Count/TotalPop.Count,
           hawaii.Percent = 100*Race.Nat.HI.Count/TotalPop.Count,
           white.Percent = 100*Race.White.Count/TotalPop.Count,
           other.Percent =100*Race.Other.Count/TotalPop.Count
           ) %>%
    select(region, contains("Percent")) %>%
    gather("demo", "Percent", contains("Percent")) %>%
    mutate(demo = gsub("\\.Percent", "", demo),
           race_cat = factor(demo, 
                             levels = nation, 
                             labels = nation_labels)) %>%
    mutate(group = "US Population") %>%
    full_join(sample_nation) %>%
    mutate(race_cat = factor(race_cat, levels = nation_labels, 
                           labels = nation_labels_breaks)) %>%
  filter(!is.na(region)) %>%
  ggplot(aes(x = race_cat, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 5), 
            position = position_dodge(1), size= 2) +
  facet_wrap(~region, scales = "free") +
  labs(x = "", fill = "")+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_minimal(base_size = 8)+
  theme(legend.position = "top") 
```

## Ethnicity by region

```{r, out.width='100%'}

sample_nation = scored %>%
  filter(!is.na(latinx) & !is.na(region)) %>%
  group_by(latinx, region) %>%
  summarize(Count = n()) %>%
  group_by(region) %>%
  mutate(Percent = 100*Count/sum(Count)) %>%
  mutate(group = "RAPID") %>%
  filter(latinx == 1)

pop %>%
  filter(!is.na(region)) %>%
  select(region, TotalPop.Count, 
         (contains("Race") & contains("Count"))) %>%
  gather(demo, count, -region) %>%
    group_by(region, demo) %>%
    summarize(count = sum(count)) %>%
    spread(demo, count) %>%
    mutate(Percent = 100*Race.Hispanic.Count/TotalPop.Count) %>%
    select(region, contains("Percent")) %>%
    mutate(group = "US Population") %>%
    full_join(sample_nation) %>%
  ggplot(aes(x = region, y = Percent, group = group)) +
  geom_bar(aes(fill = group),
           stat = "identity", position = "dodge") +
  geom_text(aes(label = round(Percent, 1), y = Percent + 2), 
            position = position_dodge(1), size= 2) +
  labs(x = "", fill = "", 
       title = "Representation of Hispanic/Latinx Caregivers by region")+
  theme_minimal(base_size = 8)+
  theme(legend.position = "top") 
```
