<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Sihong" />


<title>Childcare Special Topic</title>

<script src="site_libs/header-attrs-2.5/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Reports for RAPID R3</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Trends
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="demographics.html">Demographics</a>
    </li>
    <li>
      <a href="trend_mental.html">Caregiver mental health</a>
    </li>
    <li>
      <a href="trend_child.html">Child behavior</a>
    </li>
    <li>
      <a href="change_over_time.html">Change over time</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Specific groups</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="disability.html">Children with disabilities</a>
        </li>
        <li>
          <a href="access_by_race.html">Race/Ethnicity</a>
        </li>
        <li>
          <a href="single.html">Single parents</a>
        </li>
        <li>
          <a href="poverty.html">Low-income households</a>
        </li>
        <li>
          <a href="inequality.html">racial_inequality</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="canary.html">Family Conflict (summer)</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Curves</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="spline_final.html">Final Spline Analyses</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Policy-relevant variables</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="policy.html">Policy-relevant variables</a>
        </li>
        <li>
          <a href="policy_state.html">By states</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="wellbeing_states.html">State-level trajectories</a>
    </li>
    <li>
      <a href="social_support.html">Social support</a>
    </li>
    <li>
      <a href="hotspots.html">covid Hotspots</a>
    </li>
    <li>
      <a href="school_childcare.html">School reopening</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Material hardship</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="social_support2.html">Additional hardship and support</a>
        </li>
        <li>
          <a href="hardship_cares.html">Hardship trends post CARES</a>
        </li>
        <li>
          <a href="usda.html">Food insecurity and hardship</a>
        </li>
        <li>
          <a href="mh_followup.html">Material hardship details</a>
        </li>
        <li>
          <a href="material_hardship_01_2021.html">Material hardship January 2021</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="kinder.html">Kindergarten</a>
    </li>
    <li>
      <a href="state_policy.html">State legislation</a>
    </li>
    <li>
      <a href="child_health.html">Well-baby and vaccines</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Childcare</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="childcare.html">Changes in childcare (May)</a>
        </li>
        <li>
          <a href="propensity.html">Effect of childcare (prop score)</a>
        </li>
        <li>
          <a href="Return-to-Previous-Childcare.html">Returning to previous childcare</a>
        </li>
        <li>
          <a href="Childcare-descriptives---SL.html">Childcare descriptives</a>
        </li>
        <li>
          <a href="Childcare-Special-Topic.html">Childcare special topic</a>
        </li>
        <li>
          <a href="childcare_trends.html">Follow-up on trends</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="winter_is_coming.html">Covid cases rising</a>
    </li>
    <li>
      <a href="Family-Conflict-based-on-Master-Data.html">Family conflict (fall)</a>
    </li>
    <li>
      <a href="children_with_disability.html">Families of children with disability</a>
    </li>
    <li>
      <a href="stm_open.html">Structural topic modeling</a>
    </li>
    <li>
      <a href="food_insecurity.html">Food insecurity</a>
    </li>
    <li>
      <a href="online_learning.html">Online learning</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    RISER
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="riser1.html">Discrimination and concerns for children</a>
    </li>
    <li>
      <a href="riser_0908.html">Access to resources</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    By state
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="state_AZ_report.html">Arizona</a>
    </li>
    <li>
      <a href="state_CA_report.html">California</a>
    </li>
    <li>
      <a href="state_FL_report.html">Florida</a>
    </li>
    <li>
      <a href="state_GA_report.html">Georgia</a>
    </li>
    <li>
      <a href="state_IL_report.html">Illinois</a>
    </li>
    <li>
      <a href="state_MI_report.html">Michigan</a>
    </li>
    <li>
      <a href="state_NC_report.html">North Carolina</a>
    </li>
    <li>
      <a href="state_NY_report.html">New York</a>
    </li>
    <li>
      <a href="state_OH_report.html">Ohio</a>
    </li>
    <li>
      <a href="state_OR_report.html">Oregon</a>
    </li>
    <li>
      <a href="state_PA_report.html">Pennsylvania</a>
    </li>
    <li>
      <a href="state_TX_report.html">Texas</a>
    </li>
    <li>
      <a href="state_VA_report.html">Virginia</a>
    </li>
    <li>
      <a href="state_WA_report.html">Washington</a>
    </li>
    <li>
      <a href="state_WI_report.html">Wisconsin</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Groups
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="group_single_report.html">Single caregivers</a>
    </li>
    <li>
      <a href="group_latinx_report.html">Latinx caregivers</a>
    </li>
    <li>
      <a href="group_black_report.html">Black caregivers</a>
    </li>
    <li>
      <a href="group_poverty150_report.html">Low income caregivers</a>
    </li>
    <li>
      <a href="group_disability_report.html">Children with disabilities</a>
    </li>
  </ul>
</li>
<li>
  <a href="variable_list.html">Variables</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Open-ended responses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="raw_open.html">All responses</a>
    </li>
    <li>
      <a href="open_q1.html">Challenges</a>
    </li>
    <li>
      <a href="open_q2.html">What's helping</a>
    </li>
    <li>
      <a href="open_q3.html">Community reopening</a>
    </li>
    <li>
      <a href="open_q4.html">Employment/school reopening</a>
    </li>
    <li>
      <a href="open_q7.html">Education (older children)</a>
    </li>
    <li>
      <a href="open_q8.html">Education (young children)</a>
    </li>
    <li>
      <a href="open_q9.html">Information for policy makers</a>
    </li>
    <li>
      <a href="open_q5.html">Anything else</a>
    </li>
    <li>
      <a href="open_q10.html">Child care provider contribution</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/sjweston/Rapid-R3-Website">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Childcare Special Topic</h1>
<h4 class="author">Sihong</h4>
<h4 class="date">10/8/2020</h4>

</div>


<div id="before-covid-19-childcare-situations" class="section level1">
<h1>Before COVID-19, Childcare Situations</h1>
<div id="percentage-of-families-using-out-of-home-childcare" class="section level2">
<h2>Percentage of Families Using Out-of-Home Childcare</h2>
<div id="total-responses" class="section level3">
<h3>Total Responses</h3>
<p>Out of the 1280 respondents, there were 49.77% of caregivers reporting using out-of-home childcare before COVID-19.</p>
<pre><code>## # A tibble: 1 x 2
##       n Percent
##   &lt;int&gt;   &lt;dbl&gt;
## 1  1280    49.8</code></pre>
</div>
<div id="breakdown-by-race" class="section level3">
<h3>Breakdown by Race</h3>
<p>Before COVID-19, there were 54.72% of Black caregivers, 49.73% of White caregivers, and 47.70% of Latinx caregivers reporting using out-of-home childcare. The differences across racial/ethnic groups were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 1279 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 1.4499, df = 2, p-value = 0.4843</code></pre>
</div>
<div id="breakdown-by-income" class="section level3">
<h3>Breakdown by Income</h3>
<p>Before COVID-19, both low-income and high-income families reported similar percentage of using out-of-home childcare.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 207 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 0.022544, df = 1, p-value = 0.8806</code></pre>
</div>
<div id="breakdown-by-single-parent-status" class="section level3">
<h3>Breakdown by Single Parent Status</h3>
<p>Before COVID-19, single parents reported slightly more usage of out-of-home childcare. However, the differences were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 1278 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 0.2855, df = 1, p-value = 0.5931</code></pre>
</div>
<div id="breakdown-by-child-disability-status" class="section level3">
<h3>Breakdown by Child Disability Status</h3>
<p>Before COVID-19, parents of children with disability reported less usage of out-of-home childcare. However, the differences were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 1280 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 0.3124, df = 1, p-value = 0.5762</code></pre>
</div>
</div>
<div id="important-reasons-caregivers-selected-pre-covid-childcare-arrangements" class="section level2">
<h2>Important Reasons Caregivers Selected Pre-COVID Childcare Arrangements</h2>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>*Note. Lower mean rank scores indicates more important reasons for selecting childcare arrangements.</p>
</div>
<div id="important-itmes-caregivers-want-to-improve-in-pre-covid-childcare-arrangements" class="section level2">
<h2>Important Itmes Caregivers Want to Improve in Pre-COVID Childcare Arrangements</h2>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>*Note. Lower mean rank scores indicates items that caregivers want to improve the most.</p>
</div>
</div>
<div id="childcare-situations-after-covid-19" class="section level1">
<h1>Childcare Situations After COVID-19</h1>
<div id="caregivers-looking-for-childcare-currently" class="section level2">
<h2>Caregivers Looking for Childcare Currently</h2>
<div id="total-responses-1" class="section level3">
<h3>Total Responses</h3>
<p>Out of the 1280 respondents, there were 14.61% of caregivers looking for childcare currently.</p>
<pre><code>## # A tibble: 1 x 2
##       n Percent
##   &lt;int&gt;   &lt;dbl&gt;
## 1  1280    14.6</code></pre>
</div>
<div id="breakdown-by-race-1" class="section level3">
<h3>Breakdown by Race</h3>
<p>There were 25.47% of Black caregivers, 13.58% of White caregivers, and 13.81% of Latinx caregivers reporting currently looking for childcare. The differences across racial/ethnic groups were statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 1278 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 10.883, df = 2, p-value = 0.004333</code></pre>
</div>
<div id="breakdown-by-income-1" class="section level3">
<h3>Breakdown by Income</h3>
<p>There were 20.59% of low-income caregivers and 15.83% of high-income caregivers reporting currently looking for childcare. However, the differences across the two income groups were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 207 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 0.7204, df = 1, p-value = 0.396</code></pre>
</div>
<div id="breakdown-by-single-parent-status-1" class="section level3">
<h3>Breakdown by Single Parent Status</h3>
<p>There were 20.30% of single-parent caregivers and 13.97% of non-single-parent caregivers reporting currently looking for childcare. The differences across the two groups was marginally statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 1277 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 3.801, df = 1, p-value = 0.05122</code></pre>
</div>
<div id="breakdown-by-child-disability-status-1" class="section level3">
<h3>Breakdown by Child Disability Status</h3>
<p>There were 22.2% of caregivers of children with disability and 14.45% of caregivers of children without disability reporting currently looking for childcare. However, The differences across the two groups not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(ccare$post_lfcc, ccare$disability_cat)
## p-value = 0.2677
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.5503895 4.4049228
## sample estimates:
## odds ratio 
##    1.68978</code></pre>
<p>*Note. Small sample of children with disability (n = 27)</p>
</div>
</div>
<div id="among-caregivers-currently-looking-for-childcare-challenges-caregivers-are-experiences-with-childcare" class="section level2">
<h2>Among Caregivers Currently Looking for Childcare, Challenges Caregivers are Experiences with Childcare</h2>
<p>*Note.<br />
1) This section only included respondents who reported currently looking for childcare (n = 187)<br />
2) With relatively small sample size, results need to be interpreted cautiously</p>
<div id="challenges-finding-childcare" class="section level3">
<h3>Challenges Finding Childcare</h3>
<div id="total-responses-2" class="section level4">
<h4>Total Responses</h4>
<p>Out of the 187 respondents, there were 88.24% of caregivers reporting experiencing challenges finding childcare.</p>
<pre><code>## # A tibble: 1 x 2
##       n Percent
##   &lt;int&gt;   &lt;dbl&gt;
## 1   187    88.2</code></pre>
</div>
<div id="breakdown-by-race-2" class="section level4">
<h4>Breakdown by Race</h4>
<p>There were 81.84% of Black caregivers, 87.40% of White caregivers, and 96.97% of Latinx caregivers reporting currently experiencing challenges finding childcare. The differences across racial/ethnic groups were not statistically significant. <img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(ccare_cg$post_cg_fd, ccare_cg$race_ethnic)
## p-value = 0.1412
## alternative hypothesis: two.sided</code></pre>
</div>
<div id="breakdown-by-income-2" class="section level4">
<h4>Breakdown by Income</h4>
<p>There were 92.86% of low-income caregivers and 81.82% of high-income caregivers currently experiencing challenges finding childcare. The differences across the two groups were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(ccare_cg$post_cg_fd, ccare_cg$poverty_cat)
## p-value = 0.6283
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##    0.2399918 152.9008536
## sample estimates:
## odds ratio 
##   2.814317</code></pre>
<p>*Note. Very small sample size.</p>
</div>
<div id="breakdown-by-single-parent-status-2" class="section level4">
<h4>Breakdown by Single Parent Status</h4>
<p>There were 85.19% of single-parent caregivers and 88.75% of non-single-parent caregivers currently experiencing challenges finding childcare. The differences across the two groups were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(ccare_cg$post_cg_fd, ccare_cg$single_cat)
## p-value = 0.5312
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.2129193 3.2306045
## sample estimates:
## odds ratio 
##  0.7302162</code></pre>
</div>
<div id="breakdown-by-child-disability-status-2" class="section level4">
<h4>Breakdown by Child Disability Status</h4>
<p>There were 83.33% of caregivers of children with disability and 88.4% of caregivers of children without disability currently experiencing challenges finding childcare. The differences across the two groups were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(ccare_cg$post_cg_fd, ccare_cg$disability_cat)
## p-value = 0.5332
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##   0.06863057 32.49950916
## sample estimates:
## odds ratio 
##  0.6579698</code></pre>
<p>*Note. Small sample size of children with disability (n = 27).</p>
</div>
</div>
<div id="challenges-affording-childcare-among-caregivers-currently-looking-for-childcare" class="section level3">
<h3>Challenges Affording Childcare Among Caregivers Currently Looking for Childcare</h3>
<p>*Note. This section has small numbers of respondents (n = 187). Interpret results with causion</p>
<div id="total-responses-3" class="section level4">
<h4>Total Responses</h4>
<p>Out of the 187 respondents who are currently looking for childcare, there were 68.45% of caregivers reporting experiencing challenges affording childcare.</p>
<pre><code>## # A tibble: 1 x 2
##       n Percent
##   &lt;int&gt;   &lt;dbl&gt;
## 1   187    68.4</code></pre>
</div>
<div id="breakdown-by-race-3" class="section level4">
<h4>Breakdown by Race</h4>
<p>There were 81.48% of Black caregivers, 62.99% of White caregivers, and 78.79% of Latinx caregivers reporting currently experiencing challenges affording childcare. The differences across racial/ethnic groups were marginally statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 187 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 5.508, df = 2, p-value = 0.06368</code></pre>
</div>
<div id="breakdown-by-income-3" class="section level4">
<h4>Breakdown by Income</h4>
<p>There were 85.71% of low-income caregivers and 68.18% of high-income caregivers currently experiencing challenges affording childcare. The differences across the two groups were not statistically significant (becuase of the small sample size).</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  table(ccare_cg$post_cg_af, ccare_cg$poverty_cat)
## p-value = 0.4315
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##   0.410463 31.642472
## sample estimates:
## odds ratio 
##   2.725649</code></pre>
<p>*Note: Very small sample size.</p>
</div>
<div id="breakdown-by-single-parent-status-3" class="section level4">
<h4>Breakdown by Single Parent Status</h4>
<p>There were 74.07% of single-parent caregivers and 67.50% of non-single-parent caregivers currently experiencing challenges affording childcare. The differences across the two groups were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 187 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 0.4623, df = 1, p-value = 0.4965</code></pre>
</div>
<div id="breakdown-by-child-disability-status-3" class="section level4">
<h4>Breakdown by Child Disability Status</h4>
<p>There were 66.67% of caregivers of children with disability and 68.51% of caregivers of children without disability currently experiencing challenges affording childcare. The differences across the two groups were not statistically significant.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre><code>## Number of cases in table: 187 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 0.00912, df = 1, p-value = 0.9239
##  Chi-squared approximation may be incorrect</code></pre>
</div>
</div>
<div id="challenges-in-childcare-that-caregivers-are-facing" class="section level3">
<h3>Challenges in Childcare that Caregivers are Facing</h3>
<p>Among all the caregivers currently looking for childcare, the main challenges they face include:<br />
1) can’t find a child care arrangement where they can be confident their child will not be exposed to COVID-19 (51.87%)<br />
2) regular childcare program was closed (35.29%)<br />
3) no longer be able to afford childcare (24.60%)<br />
4) regular childcare program was open but no longer meet needs (11.23%)<br />
5) other reasons.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="caregivers-perception-about-governments-actions-to-support-childcare" class="section level1">
<h1>Caregivers’ Perception About Government’s Actions to Support Childcare</h1>
<div id="caregivers-reports-on-whether-the-government-is-doing-enough-to-support-childcare" class="section level2">
<h2>Caregivers’ Reports on Whether the Government is Doing Enough to Support Childcare</h2>
<div id="total-responses-4" class="section level3">
<h3>Total Responses</h3>
<p>There were 50.7% of caregivers thinking the government should do a lot more to support childcare; 23.44% reporting the government should do somewhat more, and only 8.20% of caregivers thinking the government has done enough to support childcare.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Note. 0 = not sure, 1 = doing enough, 2 = should do somewhat more, 3 = should do a lot more.</p>
</div>
<div id="comparison-across-raceethnicity-groups" class="section level3">
<h3>Comparison Across Race/Ethnicity Groups</h3>
<p>The average satisfaction about government’s actions to support childcare in Black, Latinx, and White caregivers were 2.21, 2.02, and 2.08, respectively (with higher score indicating reduced satisfaction). ANOVA suggested that the differences across the three groups were not statistically significant.</p>
<pre><code>## # A tibble: 4 x 2
##   race_ethnic post_gov_mn
##   &lt;chr&gt;             &lt;dbl&gt;
## 1 Black              2.21
## 2 Latinx             2.02
## 3 White              2.08
## 4 &lt;NA&gt;               1</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: post_gov
##               Df  Sum Sq Mean Sq F value Pr(&gt;F)
## race_ethnic    2    2.55  1.2761  0.9937 0.3705
## Residuals   1273 1634.77  1.2842</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  ccare_10$post_gov and ccare_10$race_ethnic 
## 
##        Black Latinx
## Latinx 0.48  -     
## White  0.52  0.52  
## 
## P value adjustment method: holm</code></pre>
</div>
<div id="comparison-across-income-groups" class="section level3">
<h3>Comparison Across Income Groups</h3>
<p>The average satisfaction about government’s actions to support childcare in high- and low-income caregivers were 2.02 and 1.87, respectively (with higher score indicating reduced satisfaction). t test suggested that the differences across the two groups were not statistically significant.</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ccare_10$post_gov by ccare_10$poverty_cat
## t = 0.85861, df = 124.3, p-value = 0.3922
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.2034878  0.5153100
## sample estimates:
## mean in group High Income  mean in group Low Income 
##                  2.021583                  1.865672</code></pre>
</div>
<div id="comparison-across-single-parent-status" class="section level3">
<h3>Comparison Across Single Parent Status</h3>
<p>The average satisfaction about government’s actions to support childcare in single- and non-single caregivers were 2.28 and 2.06, respectively (with higher score indicating reduced satisfaction). t test suggested that the differences across the two groups were statistically significant (p &lt; .05). Single parents were less satisfied with the government’s childcare actions.</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ccare_10$post_gov by ccare_10$single_cat
## t = -2.3749, df = 173.93, p-value = 0.01864
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.40837990 -0.03767832
## sample estimates:
##   mean in group Dual parent mean in group Single parent 
##                    2.055166                    2.278195</code></pre>
</div>
<div id="comparison-across-child-disability-status" class="section level3">
<h3>Comparison Across Child Disability Status</h3>
<p>The average satisfaction about government’s actions to support childcare in caregivers of children with and without disability were 1.73 and 2.08, respectively (with higher score indicating reduced satisfaction). t test suggested that the differences across the two groups were not statistically significant.</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ccare_10$post_gov by ccare_10$disability_cat
## t = 1.3608, df = 25.773, p-value = 0.1853
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.1805116  0.8868388
## sample estimates:
##         mean in group No disability mean in group Child with disability 
##                            2.083933                            1.730769</code></pre>
</div>
</div>
<div id="brightspots-caregivers-perceived-in-governments-actions-to-support-childcare" class="section level2">
<h2>Brightspots Caregivers Perceived in Government’s Actions to Support Childcare</h2>
<p>Some caregivers perceived the “bright spots” in government’s actions to support childcare as below:<br />
1) Close childcare center to keep kids safe(38.44%)<br />
2) Reopening childcare to allow essential workers and others go to work (35.00%)<br />
3) Publish health standards to keep kids safe (34.69%)<br />
Only few caregivers perceived government’s actions in providing funds to keep childcare open, paying staff more, reducing or eliminating tuition and fees to make childcare more affordable as bright spots.<br />
Additionally, 36.25% of caregivers responded “don’t know/can’t think of any bright spots”.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
</div>
<div id="caregivers-perception-on-what-are-still-needed-to-address-current-concerns-in-childcare" class="section level2">
<h2>Caregivers’ Perception on What are Still Needed to Address Current Concerns in Childcare</h2>
<p>Caregivers reported that actions by government below were still needed to support childcare and address current concerns:<br />
1) Support the well-being of early childhood educators by ensuring that they have sufficient compensation and benefits (68.28%)<br />
2) Ensure more parents have access to child care by making more parents eligible for child care subsidies/assistance (59.14%)<br />
3) Stabilize and maintain the supply of child care programs by providing financial assistance to providers (51.80%)<br />
4) Increasing the amount of child care subsidies do parents don’t have to pay as much (50.23%)</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
</div>
</div>
<div id="what-would-make-caregivers-feel-they-have-a-better-childcare-plan-for-next-month" class="section level1">
<h1>What Would Make Caregivers Feel They Have a Better Childcare Plan for Next Month</h1>
<p>Caregivers reported that below actions will make them feel that they have a better childcare plan for next month:<br />
1) Flexible work arrangement (43.59%)<br />
2) Financial resources for child care or other expenses (38.44%)<br />
3) Help from relatives and neighbors (30.00%)<br />
4) More guidance on children’s health &amp; safety in child care or camp (28.44%)<br />
5) Paid timeoff from employer (22.34%)<br />
5) More information or services from your local school system or government (22.34%)<br />
6) Camp or child care options from your local school system or government (19.45%)<br />
7) Help locating available child care (18.98%)<br />
8) Parent support groups or parenting resources (17.89%)</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
</div>
<div id="what-caregivers-consider-as-affordable-childcare-for-all-their-children" class="section level1">
<h1>What Caregivers Consider as Affordable Childcare for All Their Children</h1>
<p>Majority of caregivers reported that childcare expenses accounting for 10%-20% of household income (36.8%) or 5-9% of household income (36.25%) as affordable childcare.</p>
<p><img src="Childcare-Special-Topic_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Note. 1 = &gt;30% of household income, 2 = 20%-30% of household income, 3 = 10%-20% of household income, 4 = 5-9% of household income, 5 = 1-4% of household income.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
